Fri, 02 Jun 2023 08:37:34 GMT
cathAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '? = 'online'&& ?='offline' THEN 'offline'
       WHEN ? = 'offline'&& ?='onli...' at line 3
    at Query.Sequence._packetToError (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Pool.query (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:25:35)
    at step (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:33:23)
    at Object.next (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:14:53)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sat, 03 Jun 2023 20:57:54 GMT
cathAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '? = 'online'AND ?='offline' THEN 'offline'
       WHEN ? = 'offline'AND ?='on...' at line 3
    at Query.Sequence._packetToError (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Pool.query (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:35:35)
    at step (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:33:23)
    at Object.next (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:14:53)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sat, 03 Jun 2023 21:01:05 GMT
cathAll error
Stack: Error: ER_NO_SUCH_TABLE: Table 'servermanagement.server' doesn't exist
    at Query.Sequence._packetToError (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Pool.query (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:35:35)
    at step (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:33:23)
    at Object.next (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:14:53)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sat, 03 Jun 2023 21:01:16 GMT
cathAll error
Stack: Error: ER_NO_SUCH_TABLE: Table 'servermanagement.server' doesn't exist
    at Query.Sequence._packetToError (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Pool.query (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:35:35)
    at step (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:33:23)
    at Object.next (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:14:53)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sat, 03 Jun 2023 21:03:31 GMT
cathAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE serverId=server.serverId' at line 7
    at Query.Sequence._packetToError (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Pool.query (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:37:35)
    at step (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:33:23)
    at Object.next (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:14:53)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sat, 03 Jun 2023 21:04:02 GMT
cathAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'server.serverId' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Pool.query (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:37:35)
    at step (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:33:23)
    at Object.next (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:14:53)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sat, 03 Jun 2023 21:07:56 GMT
cathAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Pool.query (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:37:35)
    at step (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:33:23)
    at Object.next (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:14:53)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sat, 03 Jun 2023 21:10:14 GMT
cathAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Pool.query (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:37:35)
    at step (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:33:23)
    at Object.next (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:14:53)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sat, 03 Jun 2023 21:10:57 GMT
cathAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'online' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Pool.query (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:37:35)
    at step (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:33:23)
    at Object.next (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:14:53)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sat, 03 Jun 2023 21:26:39 GMT
cathAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'online' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Pool.query (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:37:35)
    at step (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:33:23)
    at Object.next (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:14:53)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sat, 03 Jun 2023 21:26:40 GMT
cathAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'online' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Pool.query (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:37:35)
    at step (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:33:23)
    at Object.next (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:14:53)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sat, 03 Jun 2023 22:22:37 GMT
cathAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'offline' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Pool.query (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:31:35)
    at step (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:33:23)
    at Object.next (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:14:53)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sat, 03 Jun 2023 22:22:39 GMT
cathAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'offline' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Pool.query (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:31:35)
    at step (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:33:23)
    at Object.next (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:14:53)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sat, 03 Jun 2023 22:25:43 GMT
cathAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'offline' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Pool.query (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:31:35)
    at step (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:33:23)
    at Object.next (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:14:53)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sat, 03 Jun 2023 22:25:44 GMT
cathAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'offline' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Pool.query (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:31:35)
    at step (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:33:23)
    at Object.next (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:14:53)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sat, 03 Jun 2023 22:25:45 GMT
cathAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'offline' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Pool.query (C:\Users\Owner\Desktop\Studies\Server management\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:31:35)
    at step (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:33:23)
    at Object.next (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:14:53)
    at C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Owner\Desktop\Studies\Server management\Backend\src\5-logic\serverlogic.ts:4:12)
----------------------------------------------------------------------------------------------------
